name: Push Image to ECR
on: 
    push: 
        branches: 
            - main
jobs:
    create-release:
      runs-on: ubuntu-22.04
      outputs:
        version: ${{ steps.version.outputs.version }}
      steps:
        - uses: actions/Checkout@v4

        - name: Get Project Version
          id: version
          run: echo version=$(node -p "require('./package.json').version") >> $GITHUB_OUTPUT

        - uses: actions/create-release@v1
          id: create-release
          env: 
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            draft: false
            prerelease: false
            release_name: ${{ steps.version.outputs.version }}
            tag_name: ${{ steps.version.outputs.version}}

    create-artifact:
      runs-on: ubuntu-22.04
      needs: create-release
      outputs:
        version: ${{ needs.create-release.outputs.version }}
      steps:
        - uses: actions/Checkout@v4

        - name: Install Dependencies
          run: npm install

        - name: Run Tests
          run: npm run test -- --watchAll=false

        - name: Build Artifact
          run: npm run build

        - name: upload Artifact
          uses: actions/upload-artifact@v4
          with:
            name: refcard-02
            path: |
              build
              Dockerfile

    build-image:
      runs-on: ubuntu-22.04
      needs: create-artifact
      steps:
        - uses: actions/download-artifact@v4
          with:
            name: refcard-02         

        - name: Build Docker Image
          run: |
            docker build -t refcard-02 .
            
        
        - name: Login to ECR Instance
          env:
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
          run: aws ecr get-login-password --region ${{ vars.AWS_REGION }} | docker login --username AWS --password-stdin 824479776970.dkr.ecr.us-east-1.amazonaws.com


        - name: Tag Image
          run: |
            docker tag refcard-02 824479776970.dkr.ecr.us-east-1.amazonaws.com/refcard-02:latest
            docker tag refcard-02 824479776970.dkr.ecr.us-east-1.amazonaws.com/refcard-02:${{ needs.create-artifact.outputs.version }}

        - name: Push Image to ECR Instance
          run: | 
            docker push 824479776970.dkr.ecr.us-east-1.amazonaws.com/refcard-02:latest
            docker push 824479776970.dkr.ecr.us-east-1.amazonaws.com/refcard-02:${{ needs.create-artifact.outputs.version }}



        

              
                
            