name: Push Image to ECR
on: 
    push: 
        branches: 
            - main
jobs:
    create-release:
      outputs:
        upload_url: ${{ steps.create-release.outputs.upload_url }}

      runs-on: ubuntu-22.04
      steps:
        - uses: actions/Checkout@v4

        - name: Get Project Version
          id: version
          run: echo version=$(node -p "require('./package.json').version") >> $GITHUB_OUTPUT

        - uses: actions/create-release@v1
          id: create-release
          env: 
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            draft: false
            prerelease: false
            release_name: ${{ steps.version.outputs.version }}
            tag_name: ${{ steps.version.outputs.version}}

    create-artifact:
      runs-on: ubuntu-22.04
      needs: create-release
      steps:
        - uses: actions/Checkout@v4

        - name: Install Dependencies
          run: npm install

        - name: Run Tests
          run: npm run test -- --watchAll=false

        - name: Build Artifact
          run: npm run build

        - name: pack artifact
          run: zip -r refcard-02.zip ./build

        - name: Upload Artifact to Release
          uses: actions/upload-release-asset@v1.0.1
          env: 
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            upload_url: ${{ needs.create-release.outputs.upload_url }}
            asset_path: ./refcard-02.zip
            asset_name: refcard-02.zip
            asset_content_type: application/zip

        

              
                
            